# Generated by Django 4.2.18 on 2026-03-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listening_analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_youtube_id', models.CharField(blank=True, default='', max_length=20)),
                ('song_title', models.CharField(blank=True, default='', max_length=220)),
                ('genre', models.CharField(blank=True, default='unknown', max_length=80)),
                ('mood', models.CharField(blank=True, default='unknown', max_length=80)),
                ('listen_seconds', models.PositiveIntegerField(default=0)),
                ('event_type', models.CharField(choices=[('play', 'Play'), ('complete', 'Complete'), ('skip', 'Skip')], default='play', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist_user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ai_generated_playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('queries', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist_user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
